// ── Objetivos ─────────────────────────────────────────────────────────────────
export const GOALS = {
  muscle: {
    label: 'Ganar músculo',
    tag: 'Hipertrofia',
    description:
      'Aumenta el volumen muscular usando cargas moderadas-altas, repeticiones intermedias y descansos controlados para estimular el crecimiento.',
    traits: ['4–12 repeticiones por serie', 'Descansos de 60–120 seg', 'Volumen alto, intensidad moderada'],
  },
  fat: {
    label: 'Perder grasa',
    tag: 'Resistencia',
    description:
      'Maximiza el gasto calórico entrenando con repeticiones altas y descansos cortos, conservando la masa muscular existente.',
    traits: ['15–25 repeticiones por serie', 'Descansos de 30–45 seg', 'Alto volumen, menor carga'],
  },
  strength: {
    label: 'Fuerza máxima',
    tag: 'Powerlifting',
    description:
      'Desarrolla fuerza real con cargas máximas, pocas repeticiones y descansos largos que permiten una recuperación completa entre series.',
    traits: ['1–6 repeticiones por serie', 'Descansos de 2–5 min', 'Baja repetición, máxima carga'],
  },
};

// ── Splits por número de días ─────────────────────────────────────────────────
export const SPLITS = {
  2: {
    name: 'Tren Superior / Tren Inferior',
    days: [
      { label: 'Tren Superior', muscles: ['pecho', 'espalda', 'hombros', 'biceps', 'triceps'] },
      { label: 'Tren Inferior', muscles: ['cuadriceps', 'isquiotibiales', 'gluteos', 'gemelos', 'abdominales'] },
    ],
  },
  3: {
    name: 'Push / Pull / Pierna',
    days: [
      { label: 'Push — Empuje', muscles: ['pecho', 'hombros', 'triceps'] },
      { label: 'Pull — Tracción', muscles: ['espalda', 'biceps'] },
      { label: 'Pierna', muscles: ['cuadriceps', 'isquiotibiales', 'gluteos', 'gemelos', 'abdominales'] },
    ],
  },
  4: {
    name: 'Pecho+Trí / Espalda+Bí / Pierna / Hombros',
    days: [
      { label: 'Pecho + Tríceps', muscles: ['pecho', 'triceps'] },
      { label: 'Espalda + Bíceps', muscles: ['espalda', 'biceps'] },
      { label: 'Pierna', muscles: ['cuadriceps', 'isquiotibiales', 'gluteos', 'gemelos'] },
      { label: 'Hombros + Abdomen', muscles: ['hombros', 'abdominales'] },
    ],
  },
  5: {
    name: 'Un grupo muscular por día',
    days: [
      { label: 'Pecho + Abdomen', muscles: ['pecho', 'abdominales'] },
      { label: 'Espalda', muscles: ['espalda'] },
      { label: 'Pierna', muscles: ['cuadriceps', 'isquiotibiales', 'gluteos', 'gemelos'] },
      { label: 'Hombros + Abdomen', muscles: ['hombros', 'abdominales'] },
      { label: 'Brazos', muscles: ['biceps', 'triceps'] },
    ],
  },
  6: {
    name: 'PPL × 2',
    days: [
      { label: 'Push A', muscles: ['pecho', 'hombros', 'triceps'] },
      { label: 'Pull A', muscles: ['espalda', 'biceps'] },
      { label: 'Pierna A', muscles: ['cuadriceps', 'isquiotibiales', 'gluteos', 'gemelos'] },
      { label: 'Push B', muscles: ['pecho', 'hombros', 'triceps'] },
      { label: 'Pull B', muscles: ['espalda', 'biceps'] },
      { label: 'Pierna B + Abdomen', muscles: ['cuadriceps', 'isquiotibiales', 'gluteos', 'gemelos', 'abdominales'] },
    ],
  },
};

// ── Grupos musculares y ejercicios ─────────────────────────────────────────────
export const MUSCLE_GROUPS = {

  pecho: {
    label: 'Pecho',
    exercises: [
      {
        id: 'press-banca',
        images: ['https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Barbell_Bench_Press_-_Medium_Grip/0.jpg', 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Barbell_Bench_Press_-_Medium_Grip/1.jpg'],
        name: 'Press de banca plano',
        recommended: ['muscle', 'strength'],
        why: 'Activa toda la superficie del pectoral y permite mover las cargas más altas posibles. Es el ejercicio de referencia para medir la fuerza de empuje del tren superior.',
        tip: 'Retrae los omóplatos contra el banco y mantén un arco lumbar natural. Baja la barra hasta la línea de los pezones de forma controlada; no rebotes contra el pecho.',
        sets: {
          muscle:   { series: 4, reps: '8-10',  rest: '90 seg' },
          fat:      { series: 3, reps: '15-20', rest: '45 seg' },
          strength: { series: 5, reps: '3-5',   rest: '3-4 min' },
        },
      },
      {
        id: 'press-inclinado',
        images: ['https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Barbell_Incline_Bench_Press_-_Medium_Grip/0.jpg', 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Barbell_Incline_Bench_Press_-_Medium_Grip/1.jpg'],
        name: 'Press de banca inclinado',
        recommended: ['muscle'],
        why: 'Enfatiza la porción clavicular (parte alta) del pectoral, que suele quedar poco desarrollada con el press plano. Clave para un pecho completo y lleno.',
        tip: 'Ángulo entre 30–45°. Con más inclinación el deltoides anterior toma el protagonismo. La técnica es idéntica al press plano.',
        sets: {
          muscle:   { series: 4, reps: '8-10',  rest: '90 seg' },
          fat:      { series: 3, reps: '15-20', rest: '45 seg' },
          strength: { series: 4, reps: '5-6',   rest: '2-3 min' },
        },
      },
      {
        id: 'press-mancuernas',
        images: ['https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Dumbbell_Bench_Press/0.jpg', 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Dumbbell_Bench_Press/1.jpg'],
        name: 'Press con mancuernas',
        recommended: ['muscle', 'fat'],
        why: 'Mayor rango de movimiento que con barra y mayor activación de los estabilizadores. Permite detectar y corregir desequilibrios entre el lado derecho e izquierdo.',
        tip: 'Baja hasta que los codos queden ligeramente por debajo de los hombros. No choques las mancuernas en la parte alta; mantén tensión constante.',
        sets: {
          muscle:   { series: 3, reps: '10-12', rest: '75 seg' },
          fat:      { series: 3, reps: '15-20', rest: '45 seg' },
          strength: { series: 4, reps: '6-8',   rest: '2 min' },
        },
      },
      {
        id: 'fondos',
        images: ['https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Parallel_Bar_Dip/0.jpg', 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Parallel_Bar_Dip/1.jpg'],
        name: 'Fondos en paralelas',
        recommended: ['fat', 'muscle'],
        why: 'Ejercicio compuesto de peso corporal que integra pecho, tríceps y hombros. Altamente funcional y fácil de progresar añadiendo peso.',
        tip: 'Inclínate hacia delante para cargar más el pecho. Sin inclinación, el trabajo se desplaza al tríceps. Baja hasta que los codos formen ~90°.',
        sets: {
          muscle:   { series: 3, reps: '10-12', rest: '75 seg' },
          fat:      { series: 4, reps: '15+',   rest: '45 seg' },
          strength: { series: 4, reps: '6-8',   rest: '2 min' },
        },
      },
      {
        id: 'aperturas',
        images: ['https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Dumbbell_Flyes/0.jpg', 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Dumbbell_Flyes/1.jpg'],
        name: 'Aperturas con mancuernas',
        recommended: ['muscle'],
        why: 'Aísla el pectoral en el plano de apertura horizontal, produciendo un estiramiento profundo que el press no puede generar. Excelente para acabado.',
        tip: 'Codos con ligera flexión fija durante todo el movimiento. No bajes más allá del nivel del banco para no comprometer los hombros.',
        sets: {
          muscle:   { series: 3, reps: '12-15', rest: '60 seg' },
          fat:      { series: 3, reps: '20',    rest: '30 seg' },
          strength: { series: 3, reps: '10-12', rest: '60 seg' },
        },
      },
      {
        id: 'cruces-polea',
        images: ['https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Cable_Crossover/0.jpg', 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Cable_Crossover/1.jpg'],
        name: 'Cruces en polea',
        recommended: ['fat'],
        why: 'A diferencia de las mancuernas, la polea mantiene tensión constante en todo el recorrido, incluida la contracción máxima al cruzar las manos.',
        tip: 'Lleva las manos a cruzarse en el centro del cuerpo (una sobre la otra). Controla la fase de vuelta en 2–3 segundos para mayor estímulo.',
        sets: {
          muscle:   { series: 3, reps: '12-15', rest: '60 seg' },
          fat:      { series: 4, reps: '20',    rest: '30 seg' },
          strength: { series: 3, reps: '10-12', rest: '60 seg' },
        },
      },
    ],
  },

  espalda: {
    label: 'Espalda',
    exercises: [
      {
        id: 'peso-muerto',
        images: ['https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Barbell_Deadlift/0.jpg', 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Barbell_Deadlift/1.jpg'],
        name: 'Peso muerto convencional',
        recommended: ['strength'],
        why: 'El ejercicio más completo para desarrollar fuerza y masa en todo el cuerpo posterior: dorsal, trapecios, glúteos e isquiotibiales en un solo movimiento.',
        tip: 'Espalda neutra (no redondear), core activado y la barra pegada a las piernas durante todo el recorrido. Empuja el suelo, no tires hacia arriba.',
        sets: {
          muscle:   { series: 3, reps: '6-8',   rest: '2 min' },
          fat:      { series: 3, reps: '10-12', rest: '75 seg' },
          strength: { series: 5, reps: '2-4',   rest: '4-5 min' },
        },
      },
      {
        id: 'dominadas',
        images: ['https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Rocky_Pull-Ups_Pulldowns/0.jpg', 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Rocky_Pull-Ups_Pulldowns/1.jpg'],
        name: 'Dominadas con agarre prono',
        recommended: ['muscle', 'strength'],
        why: 'El mejor ejercicio de tracción para el dorsal ancho. La progresión de fuerza relativa que genera es directamente transferible a otros movimientos.',
        tip: 'Comienza desde la posición muerta (brazos totalmente extendidos). Lleva el pecho hacia la barra, no la barbilla. Evita el balanceo.',
        sets: {
          muscle:   { series: 4, reps: '6-10',  rest: '90 seg' },
          fat:      { series: 3, reps: 'max',   rest: '60 seg' },
          strength: { series: 5, reps: '3-5',   rest: '3 min' },
        },
      },
      {
        id: 'remo-barra',
        images: ['https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Bent_Over_Barbell_Row/0.jpg', 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Bent_Over_Barbell_Row/1.jpg'],
        name: 'Remo con barra Pendlay',
        recommended: ['muscle', 'strength'],
        why: 'Permite cargar mucho peso y trabaja dorsal, romboides y trapecios medios de forma conjunta. Muy efectivo para dar grosor a la espalda.',
        tip: 'Torso a ~45°, codos pegados al cuerpo al tirar. En la variante Pendlay la barra toca el suelo en cada repetición, lo que elimina el impulso.',
        sets: {
          muscle:   { series: 4, reps: '8-10',  rest: '90 seg' },
          fat:      { series: 3, reps: '15',    rest: '45 seg' },
          strength: { series: 5, reps: '3-5',   rest: '3 min' },
        },
      },
      {
        id: 'jalones',
        images: ['https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Wide-Grip_Lat_Pulldown/0.jpg', 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Wide-Grip_Lat_Pulldown/1.jpg'],
        name: 'Jalones al pecho en polea',
        recommended: ['muscle', 'fat'],
        why: 'Permite ajustar el peso fácilmente y es la alternativa ideal para quienes aún no pueden hacer dominadas. Trabaja el dorsal con buen control.',
        tip: 'Pecho erguido y ligeramente hacia atrás. Tira hacia el esternón, no hacia la cara. Retrae la escápula al bajar y controla la subida.',
        sets: {
          muscle:   { series: 3, reps: '10-12', rest: '75 seg' },
          fat:      { series: 4, reps: '15-20', rest: '45 seg' },
          strength: { series: 4, reps: '6-8',   rest: '90 seg' },
        },
      },
      {
        id: 'remo-mancuerna',
        images: ['https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/One-Arm_Dumbbell_Row/0.jpg', 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/One-Arm_Dumbbell_Row/1.jpg'],
        name: 'Remo unilateral con mancuerna',
        recommended: ['muscle'],
        why: 'Mayor rango de movimiento que el remo bilateral y permite detectar desequilibrios entre lados. Alta activación del dorsal con cargas relativamente altas.',
        tip: 'Apoya la rodilla y la mano opuesta en el banco. Tira del codo hacia el techo, no de la mano. Pausa breve en la contracción máxima.',
        sets: {
          muscle:   { series: 3, reps: '10-12 c/lado', rest: '60 seg' },
          fat:      { series: 3, reps: '15 c/lado',    rest: '45 seg' },
          strength: { series: 4, reps: '6-8 c/lado',   rest: '90 seg' },
        },
      },
      {
        id: 'remo-polea',
        images: ['https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Seated_Cable_Rows/0.jpg', 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Seated_Cable_Rows/1.jpg'],
        name: 'Remo en polea baja sentado',
        recommended: ['fat'],
        why: 'Tensión constante durante todo el recorrido. Enfatiza la retracción escapular y trabaja los romboides y trapecios medios de forma aislada.',
        tip: 'No te inclines hacia atrás al tirar: el trabajo lo hace la espalda, no el impulso del cuerpo. Tira hacia el abdomen bajo.',
        sets: {
          muscle:   { series: 3, reps: '12-15', rest: '60 seg' },
          fat:      { series: 4, reps: '20',    rest: '30 seg' },
          strength: { series: 3, reps: '8-10',  rest: '90 seg' },
        },
      },
    ],
  },

  hombros: {
    label: 'Hombros',
    exercises: [
      {
        id: 'press-militar',
        images: ['https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Barbell_Shoulder_Press/0.jpg', 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Barbell_Shoulder_Press/1.jpg'],
        name: 'Press militar con barra',
        recommended: ['strength', 'muscle'],
        why: 'El ejercicio principal para la fuerza del hombro. Activa los tres haces del deltoides más el tríceps y el core para la estabilización.',
        tip: 'Barra delante de la cara (no detrás del cuello). Bloquea el core al subir y evita arquear excesivamente la espalda baja.',
        sets: {
          muscle:   { series: 4, reps: '8-10',  rest: '90 seg' },
          fat:      { series: 3, reps: '12-15', rest: '60 seg' },
          strength: { series: 5, reps: '3-5',   rest: '3-4 min' },
        },
      },
      {
        id: 'press-arnold',
        images: ['https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Arnold_Dumbbell_Press/0.jpg', 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Arnold_Dumbbell_Press/1.jpg'],
        name: 'Press Arnold con mancuernas',
        recommended: ['muscle'],
        why: 'La rotación del antebrazo durante el movimiento activa los tres haces del deltoides en un solo ejercicio, con mayor rango de movimiento que el press estándar.',
        tip: 'Empieza con las palmas mirando hacia ti y rota al subir hasta que las palmas queden hacia delante. Movimiento controlado, sin impulso.',
        sets: {
          muscle:   { series: 3, reps: '10-12', rest: '75 seg' },
          fat:      { series: 3, reps: '15',    rest: '45 seg' },
          strength: { series: 4, reps: '6-8',   rest: '2 min' },
        },
      },
      {
        id: 'elev-laterales',
        images: ['https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Side_Lateral_Raise/0.jpg', 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Side_Lateral_Raise/1.jpg'],
        name: 'Elevaciones laterales',
        recommended: ['muscle', 'fat'],
        why: 'El ejercicio más directo para el deltoides lateral, el responsable de dar anchura y amplitud visual a los hombros. Esencial en cualquier rutina.',
        tip: 'Sube hasta paralelo al suelo (no más arriba). Codo ligeramente doblado y fijo. La bajada lenta en 2–3 segundos duplica el estímulo.',
        sets: {
          muscle:   { series: 3, reps: '12-15', rest: '60 seg' },
          fat:      { series: 4, reps: '20',    rest: '30 seg' },
          strength: { series: 3, reps: '10-12', rest: '60 seg' },
        },
      },
      {
        id: 'pajaros',
        images: ['https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Bent_Over_Dumbbell_Rear_Delt_Raise_With_Head_On_Bench/0.jpg', 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Bent_Over_Dumbbell_Rear_Delt_Raise_With_Head_On_Bench/1.jpg'],
        name: 'Pájaros — deltoides posterior',
        recommended: ['muscle'],
        why: 'Trabaja el deltoides posterior, el más olvidado y el más importante para la postura y la salud del hombro a largo plazo.',
        tip: 'Torso a 90° o sobre el banco de cara. Codos con ligera flexión fija. Piensa en abrir los brazos hacia los lados, no en subir.',
        sets: {
          muscle:   { series: 3, reps: '15',    rest: '60 seg' },
          fat:      { series: 4, reps: '20',    rest: '30 seg' },
          strength: { series: 3, reps: '12',    rest: '60 seg' },
        },
      },
      {
        id: 'face-pulls',
        images: ['https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Face_Pull/0.jpg', 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Face_Pull/1.jpg'],
        name: 'Face pulls en polea alta',
        recommended: ['muscle', 'fat'],
        why: 'Fortalece el deltoides posterior y los rotadores externos del manguito rotador. Previene lesiones de hombro y mejora la postura de la espalda alta.',
        tip: 'Polea a altura de cara. Tira hacia la nariz con los codos altos y realiza rotación externa al final. Peso ligero y repeticiones controladas.',
        sets: {
          muscle:   { series: 3, reps: '15',    rest: '60 seg' },
          fat:      { series: 4, reps: '20',    rest: '30 seg' },
          strength: { series: 3, reps: '12',    rest: '60 seg' },
        },
      },
      {
        id: 'elev-frontales',
        images: ['https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Front_Dumbbell_Raise/0.jpg', 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Front_Dumbbell_Raise/1.jpg'],
        name: 'Elevaciones frontales con disco',
        recommended: ['fat'],
        why: 'Trabaja el deltoides anterior de forma aislada. Complemento útil cuando el objetivo es el desarrollo completo del hombro.',
        tip: 'Sube hasta la altura de los ojos como máximo. No balancees el cuerpo. Agarre neutro (palmas enfrentadas) es más cómodo para el hombro.',
        sets: {
          muscle:   { series: 3, reps: '12',    rest: '60 seg' },
          fat:      { series: 3, reps: '15-20', rest: '45 seg' },
          strength: { series: 3, reps: '10',    rest: '60 seg' },
        },
      },
    ],
  },

  biceps: {
    label: 'Bíceps',
    exercises: [
      {
        id: 'curl-barra',
        images: ['https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Barbell_Curl/0.jpg', 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Barbell_Curl/1.jpg'],
        name: 'Curl con barra',
        recommended: ['muscle', 'strength'],
        why: 'Permite mover más peso que con mancuernas y activa al máximo el bíceps braquial. La barra recta o EZ da libertad para elegir la posición más cómoda.',
        tip: 'Codos fijos a los lados del torso durante todo el recorrido. Sube hasta la contracción total y baja de forma controlada en 2–3 segundos.',
        sets: {
          muscle:   { series: 4, reps: '8-10',  rest: '75 seg' },
          fat:      { series: 3, reps: '15',    rest: '45 seg' },
          strength: { series: 4, reps: '5-6',   rest: '2 min' },
        },
      },
      {
        id: 'curl-alterno',
        images: ['https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Dumbbell_Alternate_Bicep_Curl/0.jpg', 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Dumbbell_Alternate_Bicep_Curl/1.jpg'],
        name: 'Curl alterno con mancuernas',
        recommended: ['muscle', 'fat'],
        why: 'La supinación activa al alzar cada repetición activa mejor la cabeza larga del bíceps. Hacerlo alterno permite más concentración en cada lado.',
        tip: 'Supina (gira) la muñeca al subir. Completa la repetición de un brazo antes de empezar el otro. Los codos no se deben mover hacia delante.',
        sets: {
          muscle:   { series: 3, reps: '10-12 c/lado', rest: '60 seg' },
          fat:      { series: 3, reps: '15-20 c/lado', rest: '45 seg' },
          strength: { series: 3, reps: '8-10 c/lado',  rest: '90 seg' },
        },
      },
      {
        id: 'curl-martillo',
        images: ['https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Alternate_Hammer_Curl/0.jpg', 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Alternate_Hammer_Curl/1.jpg'],
        name: 'Curl martillo',
        recommended: ['muscle'],
        why: 'El agarre neutro trabaja principalmente el braquiorradial y la cabeza corta del bíceps, dando grosor al brazo desde un ángulo diferente.',
        tip: 'Palmas enfrentadas durante todo el movimiento (agarre neutro, como si sostuvieras un martillo). No rotes la muñeca.',
        sets: {
          muscle:   { series: 3, reps: '10-12', rest: '60 seg' },
          fat:      { series: 3, reps: '15-20', rest: '45 seg' },
          strength: { series: 3, reps: '8-10',  rest: '75 seg' },
        },
      },
      {
        id: 'curl-concentrado',
        images: ['https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Concentration_Curls/0.jpg', 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Concentration_Curls/1.jpg'],
        name: 'Curl concentrado',
        recommended: ['fat'],
        why: 'Apoyo del tríceps en el muslo como pivote fijo genera el mayor pico de contracción posible del bíceps. Alta activación con cargas bajas.',
        tip: 'El codo apoyado en el muslo actúa como pivote fijo: no debe moverse. Pausa de 1 segundo en la contracción máxima.',
        sets: {
          muscle:   { series: 3, reps: '12 c/lado',    rest: '60 seg' },
          fat:      { series: 3, reps: '15-20 c/lado', rest: '30 seg' },
          strength: { series: 3, reps: '8-10 c/lado',  rest: '75 seg' },
        },
      },
      {
        id: 'curl-polea',
        images: ['https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/High_Cable_Curls/0.jpg', 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/High_Cable_Curls/1.jpg'],
        name: 'Curl en polea baja',
        recommended: ['fat'],
        why: 'La polea mantiene tensión constante en el bíceps incluso en la posición extendida, algo que las mancuernas no pueden ofrecer.',
        tip: 'Mantén el codo fijo. La tensión debe sentirse tanto en la subida como en la bajada. El control excéntrico es clave aquí.',
        sets: {
          muscle:   { series: 3, reps: '12-15', rest: '60 seg' },
          fat:      { series: 4, reps: '20',    rest: '30 seg' },
          strength: { series: 3, reps: '10',    rest: '75 seg' },
        },
      },
      {
        id: 'curl-inclinado',
        images: ['https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Incline_Dumbbell_Curl/0.jpg', 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Incline_Dumbbell_Curl/1.jpg'],
        name: 'Curl inclinado en banco',
        recommended: ['muscle'],
        why: 'Con el cuerpo reclinado, el bíceps parte de una posición de mayor estiramiento que en cualquier curl estándar, generando más activación en la fase baja.',
        tip: 'Banco a 45°. Deja que el peso estire completamente el bíceps antes de subir. No uses impulso del hombro.',
        sets: {
          muscle:   { series: 3, reps: '10-12', rest: '75 seg' },
          fat:      { series: 3, reps: '15',    rest: '45 seg' },
          strength: { series: 3, reps: '8-10',  rest: '90 seg' },
        },
      },
    ],
  },

  triceps: {
    label: 'Tríceps',
    exercises: [
      {
        id: 'press-cerrado',
        images: ['https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Close-Grip_Barbell_Bench_Press/0.jpg', 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Close-Grip_Barbell_Bench_Press/1.jpg'],
        name: 'Press de banca agarre cerrado',
        recommended: ['strength', 'muscle'],
        why: 'El mejor ejercicio compuesto para el tríceps. Permite mover cargas muy altas y es directamente transferible a la mejora del press de banca estándar.',
        tip: 'Agarre ligeramente más estrecho que los hombros (no demasiado junto). Codos a 45° del torso al bajar; no los abras ni los pegues al cuerpo.',
        sets: {
          muscle:   { series: 4, reps: '8-10',  rest: '90 seg' },
          fat:      { series: 3, reps: '12-15', rest: '45 seg' },
          strength: { series: 5, reps: '3-5',   rest: '3 min' },
        },
      },
      {
        id: 'press-frances',
        images: ['https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Decline_Close-Grip_Bench_To_Skull_Crusher/0.jpg', 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Decline_Close-Grip_Bench_To_Skull_Crusher/1.jpg'],
        name: 'Press francés (Skullcrusher)',
        recommended: ['muscle'],
        why: 'Gran activador de la cabeza larga del tríceps. Permite una progresión sostenida de cargas y es excelente para dar volumen al brazo.',
        tip: 'Los codos apuntan al techo y no deben abrirse durante el movimiento. Baja la barra EZ hacia la frente, no hacia la nariz.',
        sets: {
          muscle:   { series: 3, reps: '10-12', rest: '75 seg' },
          fat:      { series: 3, reps: '15',    rest: '45 seg' },
          strength: { series: 4, reps: '6-8',   rest: '2 min' },
        },
      },
      {
        id: 'extension-polea',
        images: ['https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Triceps_Pushdown/0.jpg', 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Triceps_Pushdown/1.jpg'],
        name: 'Extensión en polea alta (Pushdown)',
        recommended: ['fat', 'muscle'],
        why: 'Tensión constante durante todo el recorrido. Muy fácil de controlar la carga. El ejercicio de acabado por excelencia para el tríceps.',
        tip: 'Codos fijos y pegados a los costados durante todo el movimiento. Extiende el brazo completamente abajo; no dejes que los codos suban.',
        sets: {
          muscle:   { series: 3, reps: '12-15', rest: '60 seg' },
          fat:      { series: 4, reps: '20',    rest: '30 seg' },
          strength: { series: 3, reps: '10',    rest: '75 seg' },
        },
      },
      {
        id: 'patada-triceps',
        images: ['https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Tricep_Dumbbell_Kickback/0.jpg', 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Tricep_Dumbbell_Kickback/1.jpg'],
        name: 'Patada de tríceps con mancuerna',
        recommended: ['fat'],
        why: 'En la extensión total el tríceps alcanza su contracción máxima. Excelente para definición y acabado del brazo posterior.',
        tip: 'Torso paralelo al suelo. El codo fijo a 90° actúa como bisagra: solo se mueve el antebrazo. Pausa de 1 segundo en la extensión.',
        sets: {
          muscle:   { series: 3, reps: '12 c/lado',    rest: '60 seg' },
          fat:      { series: 3, reps: '15-20 c/lado', rest: '30 seg' },
          strength: { series: 3, reps: '10 c/lado',    rest: '75 seg' },
        },
      },
      {
        id: 'fondos-banco',
        images: ['https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Bench_Dips/0.jpg', 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Bench_Dips/1.jpg'],
        name: 'Fondos en banco',
        recommended: ['fat'],
        why: 'Ejercicio de peso corporal accesible sin equipamiento específico. Buena activación del tríceps lateral e ideal para circuitos.',
        tip: 'Caderas pegadas al banco durante toda la bajada. No bajes más de 90° en el codo para no comprometer los hombros.',
        sets: {
          muscle:   { series: 3, reps: '12-15', rest: '60 seg' },
          fat:      { series: 4, reps: '20',    rest: '30 seg' },
          strength: { series: 3, reps: '10-12', rest: '75 seg' },
        },
      },
      {
        id: 'extension-cabeza',
        images: ['https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Cable_Rope_Overhead_Triceps_Extension/0.jpg', 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Cable_Rope_Overhead_Triceps_Extension/1.jpg'],
        name: 'Extensión sobre la cabeza con mancuerna',
        recommended: ['muscle'],
        why: 'Con el brazo elevado, la cabeza larga del tríceps parte de una posición de máximo estiramiento, generando más activación que cualquier extensión en polea.',
        tip: 'Agarra la mancuerna con ambas manos. Los codos apuntan al techo sin abrirse. Muñecas neutras durante todo el recorrido.',
        sets: {
          muscle:   { series: 3, reps: '10-12', rest: '75 seg' },
          fat:      { series: 3, reps: '15',    rest: '45 seg' },
          strength: { series: 3, reps: '8-10',  rest: '90 seg' },
        },
      },
    ],
  },

  cuadriceps: {
    label: 'Cuádriceps',
    exercises: [
      {
        id: 'sentadilla',
        images: ['https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Barbell_Squat/0.jpg', 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Barbell_Squat/1.jpg'],
        name: 'Sentadilla trasera con barra',
        recommended: ['strength', 'muscle'],
        why: 'El ejercicio más completo del tren inferior. Activa cuádriceps, glúteos e isquiotibiales simultáneamente, además del core para la estabilización.',
        tip: 'Espalda neutra, rodillas alineadas con la punta de los pies. Profundidad hasta paralelo o más. Los talones no deben despegarse del suelo.',
        sets: {
          muscle:   { series: 4, reps: '8-10',  rest: '2 min' },
          fat:      { series: 4, reps: '15-20', rest: '60 seg' },
          strength: { series: 5, reps: '3-5',   rest: '4-5 min' },
        },
      },
      {
        id: 'prensa',
        images: ['https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Leg_Press/0.jpg', 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Leg_Press/1.jpg'],
        name: 'Prensa de piernas 45°',
        recommended: ['muscle', 'fat'],
        why: 'Permite mover más carga que la sentadilla libre con menor demanda técnica y sin cargar la columna. Ideal para acumular volumen de cuádriceps.',
        tip: 'Pies a anchura de hombros en la plataforma. Profundidad completa. No bloquees las rodillas arriba ni dejes que se colapsen hacia dentro.',
        sets: {
          muscle:   { series: 4, reps: '10-12', rest: '90 seg' },
          fat:      { series: 4, reps: '15-20', rest: '60 seg' },
          strength: { series: 4, reps: '6-8',   rest: '2 min' },
        },
      },
      {
        id: 'extension-cuad',
        images: ['https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Leg_Extensions/0.jpg', 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Leg_Extensions/1.jpg'],
        name: 'Extensión de cuádriceps en máquina',
        recommended: ['fat'],
        why: 'Único ejercicio que aísla el cuádriceps en flexión de rodilla. Excelente para la definición y el acabado del muslo frontal.',
        tip: 'Ajusta el rodillo a la altura correcta (tobillo, no espinilla). Pausa de 1 segundo arriba. Baja de forma controlada en 3 segundos.',
        sets: {
          muscle:   { series: 3, reps: '12-15', rest: '60 seg' },
          fat:      { series: 4, reps: '20',    rest: '30 seg' },
          strength: { series: 3, reps: '10-12', rest: '75 seg' },
        },
      },
      {
        id: 'sent-bulgara',
        images: ['https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Split_Squat_with_Dumbbells/0.jpg', 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Split_Squat_with_Dumbbells/1.jpg'],
        name: 'Sentadilla búlgara (Split squat)',
        recommended: ['muscle'],
        why: 'Trabaja cada pierna de forma independiente, corrigiendo desequilibrios. Alta activación de cuádriceps y glúteos con menor carga total que la sentadilla bilateral.',
        tip: 'Pie trasero elevado a 40–50 cm. La rodilla delantera no debe sobrepasar los dedos del pie. Torso ligeramente inclinado hacia delante.',
        sets: {
          muscle:   { series: 3, reps: '10-12 c/lado', rest: '90 seg' },
          fat:      { series: 3, reps: '15 c/lado',    rest: '60 seg' },
          strength: { series: 4, reps: '6-8 c/lado',   rest: '2 min' },
        },
      },
      {
        id: 'zancadas',
        images: ['https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Dumbbell_Lunges/0.jpg', 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Dumbbell_Lunges/1.jpg'],
        name: 'Zancadas con mancuernas',
        recommended: ['fat'],
        why: 'Movimiento dinámico que activa cuádriceps y glúteos en patrón funcional. El desplazamiento aumenta el gasto energético respecto a ejercicios estáticos.',
        tip: 'Paso largo hacia delante. La rodilla trasera casi toca el suelo. Tronco erguido durante todo el movimiento. Empuja con el talón al subir.',
        sets: {
          muscle:   { series: 3, reps: '12 c/lado',    rest: '75 seg' },
          fat:      { series: 4, reps: '20 c/lado',    rest: '45 seg' },
          strength: { series: 3, reps: '8 c/lado',     rest: '2 min' },
        },
      },
      {
        id: 'hack-squat',
        images: ['https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Barbell_Hack_Squat/0.jpg', 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Barbell_Hack_Squat/1.jpg'],
        name: 'Hack squat en máquina',
        recommended: ['muscle', 'strength'],
        why: 'Enfatiza el vasto lateral del cuádriceps más que la sentadilla libre. Permite cargas muy altas de forma segura para la columna.',
        tip: 'Pies bajos en la plataforma para mayor enfoque en cuádriceps. Profundidad completa. Rodillas hacia afuera durante toda la bajada.',
        sets: {
          muscle:   { series: 4, reps: '8-10',  rest: '90 seg' },
          fat:      { series: 3, reps: '15',    rest: '60 seg' },
          strength: { series: 5, reps: '4-6',   rest: '2-3 min' },
        },
      },
    ],
  },

  isquiotibiales: {
    label: 'Isquiotibiales',
    exercises: [
      {
        id: 'peso-muerto-rumano',
        images: ['https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Romanian_Deadlift/0.jpg', 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Romanian_Deadlift/1.jpg'],
        name: 'Peso muerto rumano',
        recommended: ['muscle', 'strength'],
        why: 'El mejor ejercicio de bisagra de cadera para isquiotibiales. Permite cargar alto peso con un patrón de movimiento funcional directo.',
        tip: 'Cadera hacia atrás (no doblar la espalda baja). Baja hasta sentir el estiramiento en los isquios, no hasta el suelo. Espalda siempre neutra.',
        sets: {
          muscle:   { series: 4, reps: '8-10',  rest: '90 seg' },
          fat:      { series: 3, reps: '12-15', rest: '60 seg' },
          strength: { series: 4, reps: '5-6',   rest: '3 min' },
        },
      },
      {
        id: 'curl-tumbado',
        images: ['https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Lying_Leg_Curls/0.jpg', 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Lying_Leg_Curls/1.jpg'],
        name: 'Curl de pierna tumbado',
        recommended: ['muscle', 'fat'],
        why: 'El único ejercicio que trabaja los isquiotibiales en flexión de rodilla. Esencial para equilibrar el desarrollo del muslo posterior.',
        tip: 'Caderas pegadas al banco durante todo el recorrido. Sube hasta la contracción completa. Baja en 3 segundos para maximizar el estímulo.',
        sets: {
          muscle:   { series: 3, reps: '10-12', rest: '60 seg' },
          fat:      { series: 4, reps: '15-20', rest: '45 seg' },
          strength: { series: 3, reps: '8-10',  rest: '90 seg' },
        },
      },
      {
        id: 'curl-sentado',
        images: ['https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Seated_Leg_Curl/0.jpg', 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Seated_Leg_Curl/1.jpg'],
        name: 'Curl de pierna sentado',
        recommended: ['muscle'],
        why: 'En posición sentada, el isquiotibial también trabaja en extensión de cadera, generando mayor activación total que en la versión tumbada.',
        tip: 'Rodilla completamente extendida al inicio de cada repetición. Tira lento y baja más lento todavía.',
        sets: {
          muscle:   { series: 3, reps: '10-12', rest: '60 seg' },
          fat:      { series: 3, reps: '15-20', rest: '45 seg' },
          strength: { series: 3, reps: '8-10',  rest: '90 seg' },
        },
      },
      {
        id: 'buenos-dias',
        images: ['https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Good_Morning/0.jpg', 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Good_Morning/1.jpg'],
        name: 'Buenos días con barra',
        recommended: ['strength'],
        why: 'Bisagra de cadera con barra en hombros. Trabaja isquiotibiales, glúteos y erectores espinales en su conjunto. Muy eficiente para fuerza posterior.',
        tip: 'Espalda recta y rodillas ligeramente dobladas. Solo te inclinas hasta donde puedas mantener la espalda neutra. No es una sentadilla.',
        sets: {
          muscle:   { series: 3, reps: '10-12', rest: '90 seg' },
          fat:      { series: 3, reps: '15',    rest: '60 seg' },
          strength: { series: 4, reps: '5-6',   rest: '2-3 min' },
        },
      },
      {
        id: 'peso-muerto-sumo',
        images: ['https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Sumo_Deadlift/0.jpg', 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Sumo_Deadlift/1.jpg'],
        name: 'Peso muerto sumo',
        recommended: ['strength'],
        why: 'La apertura de piernas activa más los isquiotibiales mediales y los aductores. Permite mover más peso total que el convencional para muchos atletas.',
        tip: 'Pies a 45°, agarre entre las piernas. Rodillas hacia afuera durante toda la subida. Cadera cerca de la barra al inicio.',
        sets: {
          muscle:   { series: 3, reps: '6-8',   rest: '2 min' },
          fat:      { series: 3, reps: '10-12', rest: '75 seg' },
          strength: { series: 5, reps: '2-4',   rest: '4-5 min' },
        },
      },
      {
        id: 'nordic-curl',
        images: ['https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Floor_Glute-Ham_Raise/0.jpg', 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Floor_Glute-Ham_Raise/1.jpg'],
        name: 'Curl nórdico',
        recommended: ['muscle', 'fat'],
        why: 'Estudios muestran que reduce un 50% el riesgo de rotura de isquiotibiales. La fase excéntrica genera un estímulo muscular excepcional.',
        tip: 'Ancla los pies bajo un banco. Cuerpo completamente recto. Baja controlando la caída con los isquios. Empuja el suelo con las manos para subir.',
        sets: {
          muscle:   { series: 3, reps: '6-8',   rest: '90 seg' },
          fat:      { series: 3, reps: '8-10',  rest: '60 seg' },
          strength: { series: 4, reps: '4-6',   rest: '2 min' },
        },
      },
    ],
  },

  gluteos: {
    label: 'Glúteos',
    exercises: [
      {
        id: 'hip-thrust',
        images: ['https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Barbell_Hip_Thrust/0.jpg', 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Barbell_Hip_Thrust/1.jpg'],
        name: 'Hip thrust con barra',
        recommended: ['muscle', 'fat'],
        why: 'El hip thrust registra la mayor activación EMG del glúteo mayor de todos los ejercicios conocidos. Es el referente absoluto para el desarrollo de glúteos.',
        tip: 'Hombros en el banco, pies plantados a la anchura de las caderas. Empuja con los talones y eleva las caderas hasta formar una línea recta. Pausa 1 seg arriba.',
        sets: {
          muscle:   { series: 4, reps: '10-12', rest: '90 seg' },
          fat:      { series: 4, reps: '15-20', rest: '45 seg' },
          strength: { series: 4, reps: '6-8',   rest: '2 min' },
        },
      },
      {
        id: 'patada-polea',
        images: ['https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Glute_Kickback/0.jpg', 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Glute_Kickback/1.jpg'],
        name: 'Patada de glúteo en polea baja',
        recommended: ['fat'],
        why: 'Aísla el glúteo en extensión de cadera con tensión constante gracias a la polea. Ideal para definición y forma sin necesidad de grandes cargas.',
        tip: 'Core activado y ligeramente inclinado hacia delante. No dejes que la cadera se balancee al subir la pierna. El movimiento es solo de la cadera.',
        sets: {
          muscle:   { series: 3, reps: '15 c/lado',    rest: '60 seg' },
          fat:      { series: 4, reps: '20 c/lado',    rest: '30 seg' },
          strength: { series: 3, reps: '12 c/lado',    rest: '75 seg' },
        },
      },
      {
        id: 'sent-sumo',
        images: ['https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Goblet_Squat/0.jpg', 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Goblet_Squat/1.jpg'],
        name: 'Sentadilla sumo con mancuerna',
        recommended: ['fat', 'muscle'],
        why: 'La apertura de piernas desplaza el foco desde los cuádriceps hacia los glúteos e isquiotibiales. Gran ejercicio para quienes no tienen barra disponible.',
        tip: 'Pies a 45°, mancuerna colgando entre las piernas. Rodillas hacia afuera. Profundidad completa. Talones en el suelo.',
        sets: {
          muscle:   { series: 3, reps: '12-15', rest: '75 seg' },
          fat:      { series: 4, reps: '20',    rest: '45 seg' },
          strength: { series: 3, reps: '8-10',  rest: '90 seg' },
        },
      },
      {
        id: 'zancada-inversa',
        images: ['https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Crossover_Reverse_Lunge/0.jpg', 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Crossover_Reverse_Lunge/1.jpg'],
        name: 'Zancada inversa',
        recommended: ['fat', 'muscle'],
        why: 'Las zancadas hacia atrás cargan más el glúteo y el isquiotibial que las zancadas hacia delante, con menor estrés en la rodilla delantera.',
        tip: 'Paso largo hacia atrás, rodilla trasera casi al suelo. Empuja con el talón del pie delantero para subir. Tronco erguido.',
        sets: {
          muscle:   { series: 3, reps: '12 c/lado',    rest: '75 seg' },
          fat:      { series: 4, reps: '15 c/lado',    rest: '45 seg' },
          strength: { series: 3, reps: '8 c/lado',     rest: '2 min' },
        },
      },
      {
        id: 'abduccion',
        images: ['https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Thigh_Abductor/0.jpg', 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Thigh_Abductor/1.jpg'],
        name: 'Abducción de cadera en máquina',
        recommended: ['fat'],
        why: 'Trabaja directamente el glúteo medio y menor, que son esenciales para la estabilidad de la rodilla y la pelvis durante la marcha y la carrera.',
        tip: 'Siéntate erguido, espalda en el respaldo. Abre lento y cierra más lento todavía (3 segundos de vuelta). No uses el peso demasiado alto.',
        sets: {
          muscle:   { series: 3, reps: '15-20', rest: '60 seg' },
          fat:      { series: 4, reps: '25',    rest: '30 seg' },
          strength: { series: 3, reps: '12',    rest: '60 seg' },
        },
      },
      {
        id: 'step-up',
        images: ['https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Barbell_Step_Ups/0.jpg', 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Barbell_Step_Ups/1.jpg'],
        name: 'Step-up con mancuernas',
        recommended: ['fat', 'muscle'],
        why: 'Movimiento unilateral funcional que activa glúteo y cuádriceps de forma natural. Con ritmo elevado tiene un componente cardiovascular importante.',
        tip: 'Sube con el talón del pie que está en el escalón, no con los dedos. El pie de abajo no debe empujar para ayudar. Tronco erguido.',
        sets: {
          muscle:   { series: 3, reps: '12 c/lado',    rest: '60 seg' },
          fat:      { series: 4, reps: '15 c/lado',    rest: '30 seg' },
          strength: { series: 3, reps: '8 c/lado',     rest: '90 seg' },
        },
      },
    ],
  },

  gemelos: {
    label: 'Gemelos',
    exercises: [
      {
        id: 'elev-talon-pie',
        images: ['https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Rocking_Standing_Calf_Raise/0.jpg', 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Rocking_Standing_Calf_Raise/1.jpg'],
        name: 'Elevación de talones de pie con barra',
        recommended: ['muscle', 'strength'],
        why: 'Con la rodilla extendida, el gastrocnemio (la cabeza visible del gemelo) trabaja en su rango completo. Es el ejercicio más efectivo para ganar masa.',
        tip: 'Sube hasta la punta de los dedos, baja hasta el estiramiento máximo. 2 segundos arriba, 3 segundos abajo. Sin rebote.',
        sets: {
          muscle:   { series: 4, reps: '10-15', rest: '60 seg' },
          fat:      { series: 3, reps: '20-25', rest: '30 seg' },
          strength: { series: 5, reps: '6-8',   rest: '90 seg' },
        },
      },
      {
        id: 'elev-talon-sentado',
        images: ['https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Seated_Calf_Raise/0.jpg', 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Seated_Calf_Raise/1.jpg'],
        name: 'Elevación de talones sentado',
        recommended: ['muscle'],
        why: 'Con la rodilla a 90°, el gastrocnemio está relajado y el sóleo (músculo profundo) toma el protagonismo. Esencial para un gemelo completo.',
        tip: 'Pad sobre la parte baja del muslo. Rango completo de movimiento: estiramiento total abajo y contracción completa arriba.',
        sets: {
          muscle:   { series: 3, reps: '12-15', rest: '60 seg' },
          fat:      { series: 3, reps: '20',    rest: '30 seg' },
          strength: { series: 4, reps: '8-10',  rest: '75 seg' },
        },
      },
      {
        id: 'elev-talon-prensa',
        images: ['https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Calf_Press_On_The_Leg_Press_Machine/0.jpg', 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Calf_Press_On_The_Leg_Press_Machine/1.jpg'],
        name: 'Elevación de talones en prensa',
        recommended: ['muscle'],
        why: 'Permite mover mucha carga en posición cómoda y segura para la columna. Trabaja el gastrocnemio en un rango de movimiento amplio.',
        tip: 'Solo la punta de los pies en la plataforma. Rodillas ligeramente dobladas. Rango máximo de movimiento en ambas direcciones.',
        sets: {
          muscle:   { series: 4, reps: '12-15', rest: '60 seg' },
          fat:      { series: 3, reps: '20',    rest: '30 seg' },
          strength: { series: 4, reps: '8-10',  rest: '75 seg' },
        },
      },
      {
        id: 'elev-talon-unipierna',
        images: ['https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Donkey_Calf_Raises/0.jpg', 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Donkey_Calf_Raises/1.jpg'],
        name: 'Elevación de talones unilateral',
        recommended: ['fat', 'muscle'],
        why: 'Al trabajar una pierna sola, es más fácil detectar y corregir desequilibrios. El control del movimiento aumenta notablemente.',
        tip: 'Agárrate a un soporte solo con un dedo para el equilibrio (no para apoyarte). Rango completo: estira completamente el gemelo abajo.',
        sets: {
          muscle:   { series: 3, reps: '12 c/lado',    rest: '60 seg' },
          fat:      { series: 3, reps: '20 c/lado',    rest: '30 seg' },
          strength: { series: 4, reps: '8 c/lado',     rest: '75 seg' },
        },
      },
      {
        id: 'elev-mancuerna',
        images: ['https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Standing_Dumbbell_Calf_Raise/0.jpg', 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Standing_Dumbbell_Calf_Raise/1.jpg'],
        name: 'Elevación de talones con mancuerna',
        recommended: ['fat'],
        why: 'Versión accesible sin máquina específica. Con el pie elevado en un escalón se consigue el rango completo de movimiento.',
        tip: 'La mancuerna en la misma mano que la pierna que trabaja. Pie elevado para mayor rango. Control total del movimiento.',
        sets: {
          muscle:   { series: 3, reps: '15',    rest: '60 seg' },
          fat:      { series: 4, reps: '25',    rest: '30 seg' },
          strength: { series: 3, reps: '10',    rest: '75 seg' },
        },
      },
      {
        id: 'salto-cuerda',
        images: ['https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Rope_Jumping/0.jpg', 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Rope_Jumping/1.jpg'],
        name: 'Salto a la comba',
        recommended: ['fat'],
        why: 'Trabaja los gemelos de forma pliométrica y cardiovascular al mismo tiempo. Alto gasto calórico y mejora de la coordinación.',
        tip: 'Aterriza siempre en la punta del pie, nunca con el talón. Son las muñecas las que hacen girar la cuerda, no los brazos.',
        sets: {
          muscle:   { series: 3, reps: '1 min',  rest: '60 seg' },
          fat:      { series: 5, reps: '2 min',  rest: '30 seg' },
          strength: { series: 3, reps: '1 min',  rest: '60 seg' },
        },
      },
    ],
  },

  abdominales: {
    label: 'Abdominales',
    exercises: [
      {
        id: 'plancha',
        images: ['https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Plank/0.jpg', 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Plank/1.jpg'],
        name: 'Plancha isométrica',
        recommended: ['muscle', 'fat'],
        why: 'Activa todo el core (transverso, recto, oblicuos) de forma funcional y simultánea. Clave para proteger la columna bajo carga en cualquier otro ejercicio.',
        tip: 'Cuerpo completamente recto de cabeza a talones. No subas las caderas ni las dejes caer. Respira de forma continua. Core activamente contraído.',
        sets: {
          muscle:   { series: 3, reps: '45 seg', rest: '60 seg' },
          fat:      { series: 4, reps: '60 seg', rest: '30 seg' },
          strength: { series: 3, reps: '45 seg', rest: '60 seg' },
        },
      },
      {
        id: 'crunch-polea',
        images: ['https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Cable_Crunch/0.jpg', 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Cable_Crunch/1.jpg'],
        name: 'Crunch en polea alta',
        recommended: ['muscle', 'fat'],
        why: 'Tensión constante durante todo el rango de movimiento. Permite añadir carga de forma progresiva, algo que el crunch en el suelo no permite.',
        tip: 'Rodillas en el suelo, tira la cuerda hacia los muslos (no hacia el suelo). El movimiento es de flexión de columna, no de cadera.',
        sets: {
          muscle:   { series: 3, reps: '12-15', rest: '60 seg' },
          fat:      { series: 4, reps: '20',    rest: '30 seg' },
          strength: { series: 3, reps: '10-12', rest: '75 seg' },
        },
      },
      {
        id: 'elev-piernas',
        images: ['https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Hanging_Leg_Raise/0.jpg', 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Hanging_Leg_Raise/1.jpg'],
        name: 'Elevación de piernas colgado',
        recommended: ['muscle', 'strength'],
        why: 'El ejercicio más completo para el abdomen inferior y el psoas. La desventaja mecánica del colgado lo hace muy exigente.',
        tip: 'Sin balanceo: el movimiento lo genera el core, no el impulso. Piernas juntas. Si no puedes en barra, usa la silla romana.',
        sets: {
          muscle:   { series: 3, reps: '10-12', rest: '60 seg' },
          fat:      { series: 4, reps: '15-20', rest: '30 seg' },
          strength: { series: 4, reps: '8-10',  rest: '75 seg' },
        },
      },
      {
        id: 'rueda-abd',
        images: ['https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Ab_Roller/0.jpg', 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Ab_Roller/1.jpg'],
        name: 'Rueda abdominal (Ab wheel)',
        recommended: ['muscle', 'strength'],
        why: 'Genera la mayor activación del recto abdominal y del serrato de todos los ejercicios de core. Extremadamente exigente.',
        tip: 'Empieza desde rodillas. Espalda neutra en todo momento; no dejes que la zona lumbar se hunda. Vuelve contraendo el core, no arqueando.',
        sets: {
          muscle:   { series: 3, reps: '8-10',  rest: '90 seg' },
          fat:      { series: 3, reps: '12',    rest: '60 seg' },
          strength: { series: 4, reps: '6-8',   rest: '90 seg' },
        },
      },
      {
        id: 'russian-twist',
        images: ['https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Russian_Twist/0.jpg', 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Russian_Twist/1.jpg'],
        name: 'Russian twist con peso',
        recommended: ['fat'],
        why: 'Trabaja los oblicuos de forma directa mediante la rotación del tronco. Los oblicuos son esenciales para la estabilidad lateral y la potencia rotatoria.',
        tip: 'Pies elevados o apoyados según nivel. Gira el torso completo (no solo los brazos). Movimiento controlado, sin impulso.',
        sets: {
          muscle:   { series: 3, reps: '20 total', rest: '60 seg' },
          fat:      { series: 4, reps: '30 total', rest: '30 seg' },
          strength: { series: 3, reps: '15 total', rest: '60 seg' },
        },
      },
      {
        id: 'dead-bug',
        images: ['https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Dead_Bug/0.jpg', 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises/Dead_Bug/1.jpg'],
        name: 'Dead bug',
        recommended: ['fat', 'muscle'],
        why: 'Activa el transverso abdominal (la faja muscular más profunda) en un patrón de movimiento seguro para la espalda. Ideal para la estabilidad lumbar.',
        tip: 'Espalda pegada al suelo en todo momento. Extiende el brazo y la pierna opuestos muy despacio, en 3–4 segundos. Sin prisa.',
        sets: {
          muscle:   { series: 3, reps: '10-12 c/lado', rest: '60 seg' },
          fat:      { series: 4, reps: '15 c/lado',    rest: '30 seg' },
          strength: { series: 3, reps: '10 c/lado',    rest: '75 seg' },
        },
      },
    ],
  },

};
